[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "test_project"
description = "Test"
authors = [
    {name = "Markus Binsteiner", email = "markus@frkl.dev"}
]
readme = "README.md"
requires-python = ">=3.9,<4.0"
keywords = []
license = "0BSD"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]
dependencies = [
]
dynamic = ["version"]


[project.optional-dependencies]

[dependency-groups]
dev = [
    "build",
    "devtools",
    "icecream",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "rich",
    "ruff",
    "snoop",
    "ty",
    "wat"
]

[project.urls]
homepage = "https://github.com/makkus/test_project"
documentation = "https://makkus.github.io/test_project"
repository = "https://github.com/makkus/test_project"

[tool.hatch.version]
source = "uv-dynamic-versioning"
fallback-version = "0.0.0"


[tool.hatch.build.targets.wheel]
packages = ["src/test_project"]

[tool.hatch.build.hooks.version]
path = "src/test_project/_version.py"
template = '''version = "{version}"
'''

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--tb=short",
    "--color=yes"
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests"
]

[tool.ruff]
line-length = 88

src = ["src", "tests"]

fix = true

# Assume Python 3.10.
target-version = "py310"

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.isort]
known-first-party = ["test_project"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
pip = ">=25.0"

[tool.pixi.pypi-dependencies]
"test_project" = { path = ".", editable = true }

[tool.pixi.feature.dev_utils.pypi-dependencies]
"" = { path = ".", editable = true, extras = ["dev"] }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"] }  # should be the same solve-group, but that doesn't seem to work with pixi currently
